# Source default setting
[ -f /etc/bashrc ] && . /etc/bashrc

# User environment PATH
PATH="$HOME/.local/bin:$HOME/bin:$PATH"
export PATH
export GAUSSDATA=/home/gauss/openGauss/data
export GAUSSHOME=/home/gauss/openGauss/install
export PATH=/home/gauss/openGauss/install/bin:$PATH
export LD_LIBRARY_PATH=/home/gauss/openGauss/install/lib:$LD_LIBRARY_PATH